### ISSUE TITLE
Can't remain hyperlink

### ISSUE THREAD

**Issue by Mister-Kin** [r12f/hexo-heading-index#5]
A good plugin. Thanks for your effort.
I noticed that this plugin can't remain hyperlink when I used hyperlink on heading.

## Some info
- hexo version: v6.0.0
- hexo theme version: next v8.9.0
- plugin version: v1.0.4

**plugin config:**
```yaml
heading_index:
  enable: true
  index_styles: "{1} {1} {1} {1} {1} {1}"
  connector: "."
  global_prefix: ""
  global_suffix: " "
  start_level: 1
```

## Expected behavior
For example, following code with heading level 1.
```markdown
# [test](https://link-example.com/)
```
It should output the heading with a hyperlink: 1 [test](https://link-example.com/)

## Actual behavior
It outputs plain text: 1 test
